{{- if and .Values.ui.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.ui.serviceAccount.name }}{{ .Values.ui.serviceAccount.name }}{{ else }}{{ $.Release.Name }}-{{ .Values.ui.name }}{{ end }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 