apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: showcase-tls
spec:
  secretName: showcase-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bcshowcase-api.dev.nborbit.ca
    - bcshowcase-traction.dev.nborbit.ca
    - bcshowcase-ui.dev.nborbit.ca
