apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: showcase-ui-route
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bcshowcase-ui.dev.nborbit.ca`)
      kind: Rule
      services:
        - name: showcase-ui-showcase-ui
          port: 3050
  tls:
    secretName: showcase-ui-tls